services:
  retail-app:
    build:
      context: .
      dockerfile: Dockerfile

    image: retail-app:4.2.0

    container_name: retail-project-app

    ports:
      - "8081:8081"

    environment:
      APP_VERSION: "4.2.0"
      APP_ENV: "UAT"
      PAYMENT_STATUS: "DEFECTIVE"

    networks:
      - retail-network

    restart: unless-stopped

networks:
  retail-network:
    driver: bridge